services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - cobre-net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - cobre-net

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - cobre-net

  mysql:
    image: mysql
    restart: always
    container_name: mysql-cbmm
    environment:
      MYSQL_DATABASE: 'accounts'
      MYSQL_USER: 'cobre'
      MYSQL_PASSWORD: 'cobre'
      MYSQL_ROOT_PASSWORD: 'cobre'
    ports:
      - '3306:3306'
    networks:
      - cobre-net

  movements-service:
    container_name: movements-service
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8091:8091"
    networks:
      - cobre-net

networks:
  cobre-net:
    driver: bridge