CREATE TABLE IF NOT EXISTS cbmm_saga (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    event_id VARCHAR(64) NOT NULL UNIQUE,
    cbmm_status VARCHAR(32) NOT NULL,
    payload JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);